.TH "qoauth_global.h" 3 "24 Jun 2009" "Version 0.1.0" "QOAuth" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qoauth_global.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal.h>\fP
.br

.SH "Detailed Description"
.PP 
This file is a part of libqoauth and is strictly internal. You should not include it in your application. Instead please use \fC#include <QtOAuth>\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for QOAuth from the source code.
