.TH "qoauth.h" 3 "31 Jul 2009" "Version 0.1.0" "QOAuth" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qoauth.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QMultiMap>\fP
.br
\fC#include 'qoauth_global.h'\fP
.br
\fC#include 'qoauth_namespace.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQOAuth::QOAuth\fP"
.br
.RI "\fIThis class provides means for interaction with network services supporting OAuth authorization scheme. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBQOAuth\fP"
.br
.RI "\fIThis namespace encapsulates all classes and definitions provided by libqoauth. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
This file is a part of libqoauth. You should not include it directly in your application. Instead please use \fC#include <QtOAuth>\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for QOAuth from the source code.
