######################################################################
# Automatically generated by qmake (2.01a) niedz. pa? 17 17:32:40 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += oauth
CONFIG -= app_bundle

# Input
SOURCES += main.cpp mainwindow.cpp
HEADERS += mainwindow.h

FORMS += \
    mainwindow.ui
